openapi: 3.0.0
info:
  title: OTT Claro Backend API
  description: API specification for OTT Claro Backend Simulation
  version: 1.0.0

servers:
  - url: /api/v1
    description: Base API path

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    StartHeaderInfo:
      type: object
      properties:
        deviceId:
          type: string
          description: Unique device identifier
        region:
          type: string
          description: User's region code
        platform:
          type: string
          description: Device platform (iOS, Android, Web, etc.)
        version:
          type: string
          description: App version

    NavigationData:
      type: object
      properties:
        structure:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              title:
                type: string
              type:
                type: string
              children:
                type: array
                items:
                  $ref: '#/components/schemas/NavigationData'

    AssetConfig:
      type: object
      properties:
        formats:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              quality:
                type: string
              codec:
                type: string
        drm:
          type: object
          properties:
            enabled:
              type: boolean
            provider:
              type: string

    MetadataConfig:
      type: object
      properties:
        fields:
          type: array
          items:
            type: string
        language:
          type: string
        format:
          type: string

security:
  - bearerAuth: []

paths:
  /user/startheaderinfo:
    post:
      summary: Initialize user session with device and region information
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartHeaderInfo'
      responses:
        '200':
          description: Session initialized successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    type: string
                  status:
                    type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /nav/data:
    get:
      summary: Retrieve hierarchical navigation structure
      tags:
        - Navigation
      parameters:
        - in: query
          name: language
          schema:
            type: string
          required: false
          description: Preferred language for navigation items
      responses:
        '200':
          description: Navigation structure retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NavigationData'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /apa/asset:
    get:
      summary: Get device-specific asset configurations
      tags:
        - Asset
      parameters:
        - in: query
          name: deviceId
          schema:
            type: string
          required: true
          description: Device identifier
        - in: query
          name: assetId
          schema:
            type: string
          required: true
          description: Asset identifier
      responses:
        '200':
          description: Asset configuration retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetConfig'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Asset not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /apa/metadata:
    get:
      summary: Retrieve content metadata and parameters
      tags:
        - Asset
      parameters:
        - in: query
          name: assetId
          schema:
            type: string
          required: true
          description: Asset identifier
        - in: query
          name: language
          schema:
            type: string
          required: false
          description: Preferred language for metadata
      responses:
        '200':
          description: Metadata configuration retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataConfig'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Asset not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'