openapi: 3.0.0
info:
  title: Video OTT Platform API
  version: 1.0.0
  description: Mock API server for Video OTT Platform providing authentication, content management, and streaming services

servers:
  - url: /api/v1
    description: API base path

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        status:
          type: string
          enum: [error]
        message:
          type: string
          description: Error message description
        code:
          type: string
          description: Optional error code for specific error types

    DeviceAuthInfo:
      type: object
      required:
        - deviceId
        - region
        - platform
        - appVersion
      properties:
        deviceId:
          type: string
          description: Unique device identifier
        region:
          type: string
          description: User's geographic region
        platform:
          type: string
          description: Device platform (e.g., iOS, Android, Web)
        appVersion:
          type: string
          description: Application version number

    SessionInfo:
      type: object
      properties:
        userId:
          type: string
          description: Unique user identifier
        displayName:
          type: string
          description: User's display name
        avatar:
          type: string
          format: uri
          description: URL to user's avatar image
        notifications:
          type: integer
          description: Number of unread notifications

    NavigationResponse:
      type: object
      properties:
        status:
          type: string
          enum: [success]
        data:
          type: object
          properties:
            navigation:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  path:
                    type: string
                  icon:
                    type: string
                  children:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        path:
                          type: string
                        icon:
                          type: string

    AssetConfig:
      type: object
      properties:
        status:
          type: string
          enum: [success]
        data:
          type: object
          properties:
            id:
              type: string
            title:
              type: string
            type:
              type: string
            duration:
              type: integer
            streamUrl:
              type: string
              format: uri
            thumbnailUrl:
              type: string
              format: uri
            availableUntil:
              type: string
              format: date-time
            isHD:
              type: boolean
            hasSubtitles:
              type: boolean
            supportedFormats:
              type: array
              items:
                type: string
            supportedResolutions:
              type: array
              items:
                type: string
            drm:
              type: object
              properties:
                provider:
                  type: string
                token:
                  type: string

    MetadataConfig:
      type: object
      properties:
        status:
          type: string
          enum: [success]
        data:
          type: object
          properties:
            assetId:
              type: string
            title:
              type: string
            description:
              type: string
            releaseYear:
              type: integer
            genres:
              type: array
              items:
                type: string
            cast:
              type: array
              items:
                type: string
            director:
              type: string
            rating:
              type: string
            language:
              type: string
            subtitles:
              type: array
              items:
                type: string
            runtime:
              type: string
            posterUrl:
              type: string
              format: uri
            trailerUrl:
              type: string
              format: uri
            tags:
              type: array
              items:
                type: string
            popularity:
              type: number
              format: float
            averageRating:
              type: number
              format: float

  parameters:
    DeviceIdHeader:
      in: header
      name: X-Device-Id
      required: true
      schema:
        type: string
      description: Unique device identifier
    RegionHeader:
      in: header
      name: X-Region
      required: true
      schema:
        type: string
      description: User's geographic region

  responses:
    UnauthorizedError:
      description: Unauthorized - Invalid or missing authentication
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    RateLimitError:
      description: Too many requests
      headers:
        X-RateLimit-Limit:
          schema:
            type: integer
          description: Number of allowed requests in the current period
        X-RateLimit-Remaining:
          schema:
            type: integer
          description: Number of remaining requests in the current period
        X-RateLimit-Reset:
          schema:
            type: integer
          description: The remaining window before the rate limit resets in seconds
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

paths:
  /user/startheaderinfo:
    post:
      summary: Initialize user session with device and region information
      description: Creates a new user session and returns user profile information based on device and region details
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/DeviceIdHeader'
        - $ref: '#/components/parameters/RegionHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceAuthInfo'
      responses:
        '200':
          description: Session initialized successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionInfo'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '429':
          $ref: '#/components/responses/RateLimitError'

  /nav/data:
    get:
      summary: Retrieve hierarchical navigation structure
      description: Returns the complete navigation menu structure including categories and subcategories
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/DeviceIdHeader'
        - $ref: '#/components/parameters/RegionHeader'
      responses:
        '200':
          description: Navigation structure retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NavigationResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '429':
          $ref: '#/components/responses/RateLimitError'

  /apa/asset:
    get:
      summary: Get device-specific asset configurations
      description: Retrieves streaming configuration for a specific asset based on device capabilities
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/DeviceIdHeader'
        - $ref: '#/components/parameters/RegionHeader'
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: Asset identifier
        - name: resolution
          in: query
          required: false
          schema:
            type: string
          description: Preferred resolution
        - name: format
          in: query
          required: false
          schema:
            type: string
          description: Preferred streaming format
      responses:
        '200':
          description: Asset configuration retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetConfig'
        '400':
          description: Missing required parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '429':
          $ref: '#/components/responses/RateLimitError'

  /apa/metadata:
    get:
      summary: Retrieve content metadata and parameters
      description: Returns detailed metadata information for a specific content asset
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/DeviceIdHeader'
        - $ref: '#/components/parameters/RegionHeader'
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: Asset identifier
        - name: language
          in: query
          required: false
          schema:
            type: string
          default: en
          description: Preferred language for metadata
      responses:
        '200':
          description: Metadata retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataConfig'
        '400':
          description: Missing required parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '429':
          $ref: '#/components/responses/RateLimitError'
