openapi: 3.0.0
info:
  title: OTT Claro Backend API
  description: |
    API Core Component for OTT Claro Backend providing user session management,
    navigation structure, asset configuration, and metadata services.
  version: 1.0.0

servers:
  - url: /api/v1
    description: Base API path

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message

    StartHeaderInfo:
      type: object
      required:
        - deviceId
        - region
        - platform
      properties:
        deviceId:
          type: string
          description: Unique device identifier
        region:
          type: string
          description: User's region code
        platform:
          type: string
          description: Device platform (iOS, Android, Web, etc.)
        language:
          type: string
          description: Preferred language code
        model:
          type: string
          description: Device model information

    StartHeaderResponse:
      type: object
      properties:
        sessionToken:
          type: string
          description: Session token for subsequent requests
        expiresIn:
          type: integer
          description: Token expiration time in seconds
        settings:
          type: object
          description: User and device specific settings

    NavigationData:
      type: object
      properties:
        structure:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              title:
                type: string
              type:
                type: string
              children:
                type: array
                items:
                  $ref: '#/components/schemas/NavigationData'

    AssetConfig:
      type: object
      properties:
        formats:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              quality:
                type: string
              codec:
                type: string
        drm:
          type: object
          properties:
            provider:
              type: string
            settings:
              type: object

    MetadataConfig:
      type: object
      properties:
        fields:
          type: array
          items:
            type: string
        localization:
          type: object
        formatting:
          type: object

security:
  - bearerAuth: []

paths:
  /user/startheaderinfo:
    post:
      summary: Initialize user session with device and region information
      tags:
        - User Session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartHeaderInfo'
      responses:
        '200':
          description: Session initialized successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartHeaderResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /nav/data:
    get:
      summary: Retrieve hierarchical navigation structure
      tags:
        - Navigation
      parameters:
        - in: query
          name: language
          schema:
            type: string
          description: Language code for localized content
        - in: query
          name: region
          schema:
            type: string
          description: Region code for filtered content
      responses:
        '200':
          description: Navigation structure retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NavigationData'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /apa/asset:
    get:
      summary: Get device-specific asset configurations
      tags:
        - Asset Configuration
      parameters:
        - in: query
          name: deviceType
          required: true
          schema:
            type: string
          description: Type of device requesting asset configuration
        - in: query
          name: assetId
          required: true
          schema:
            type: string
          description: ID of the asset to configure
      responses:
        '200':
          description: Asset configuration retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetConfig'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /apa/metadata:
    get:
      summary: Retrieve content metadata and parameters
      tags:
        - Metadata Configuration
      parameters:
        - in: query
          name: contentId
          required: true
          schema:
            type: string
          description: ID of the content to retrieve metadata for
        - in: query
          name: type
          schema:
            type: string
          description: Type of content (movie, series, episode, etc.)
        - in: query
          name: language
          schema:
            type: string
          description: Language code for localized metadata
      responses:
        '200':
          description: Metadata configuration retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataConfig'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
