openapi: 3.0.0
info:
  title: Video OTT Platform API
  version: 1.0.0
  description: Mock API server for Video OTT Platform providing authentication, content management, and streaming services

servers:
  - url: http://localhost:3000
    description: Local development server

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    StartHeaderInfo:
      type: object
      properties:
        deviceId:
          type: string
          description: Unique identifier for the device
        region:
          type: string
          description: User's region code
        platform:
          type: string
          description: Device platform (iOS, Android, Web, etc.)
        version:
          type: string
          description: App version
    NavigationData:
      type: object
      properties:
        structure:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              title:
                type: string
              type:
                type: string
              children:
                type: array
                items:
                  $ref: '#/components/schemas/NavigationData'
    AssetConfig:
      type: object
      properties:
        assetId:
          type: string
        streamingUrl:
          type: string
        quality:
          type: string
        drm:
          type: object
        subtitles:
          type: array
          items:
            type: object
            properties:
              language:
                type: string
              url:
                type: string
    MetadataConfig:
      type: object
      properties:
        contentId:
          type: string
        title:
          type: string
        description:
          type: string
        duration:
          type: integer
        rating:
          type: string
        genres:
          type: array
          items:
            type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /user/startheaderinfo:
    post:
      summary: Initialize user session with device and region information
      description: Creates a new session with the provided device and region information
      operationId: startHeaderInfo
      tags:
        - User Session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartHeaderInfo'
      responses:
        '200':
          description: Session initialized successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    type: string
                  token:
                    type: string
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /nav/data:
    get:
      summary: Retrieve hierarchical navigation structure
      description: Returns the complete navigation structure for the application
      operationId: getNavigationData
      tags:
        - Navigation
      responses:
        '200':
          description: Navigation structure retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NavigationData'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /apa/asset:
    get:
      summary: Get device-specific asset configurations
      description: Returns asset configuration based on device capabilities
      operationId: getAssetConfig
      tags:
        - Asset Management
      parameters:
        - name: assetId
          in: query
          required: true
          schema:
            type: string
        - name: deviceType
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Asset configuration retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetConfig'
        '404':
          description: Asset not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /apa/metadata:
    get:
      summary: Retrieve content metadata and parameters
      description: Returns metadata information for specified content
      operationId: getMetadataConfig
      tags:
        - Content Management
      parameters:
        - name: contentId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Metadata retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataConfig'
        '404':
          description: Content not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
