openapi: 3.0.0
info:
  title: OTT Claro Backend API
  description: |
    API specification for OTT Claro Backend Simulation providing user session management,
    navigation structure, asset configuration, and metadata services.
  version: 1.0.0

servers:
  - url: /api/v1
    description: Base API path

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    StartHeaderInfo:
      type: object
      required:
        - deviceId
        - region
      properties:
        deviceId:
          type: string
          description: Unique identifier for the device
        region:
          type: string
          description: User's region code
        deviceType:
          type: string
          description: Type of device (mobile, tablet, smart-tv, etc.)
        osVersion:
          type: string
          description: Operating system version
    StartHeaderResponse:
      type: object
      properties:
        sessionId:
          type: string
          description: Unique session identifier
        timestamp:
          type: string
          format: date-time
        status:
          type: string
          enum: [active, expired]
    NavigationData:
      type: object
      properties:
        structure:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              type:
                type: string
              children:
                type: array
                items:
                  $ref: '#/components/schemas/NavigationData'
    AssetConfig:
      type: object
      properties:
        formats:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              quality:
                type: string
              codec:
                type: string
        drm:
          type: object
          properties:
            enabled:
              type: boolean
            provider:
              type: string
    MetadataConfig:
      type: object
      properties:
        fields:
          type: array
          items:
            type: string
        language:
          type: string
        format:
          type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

security:
  - BearerAuth: []

paths:
  /user/startheaderinfo:
    post:
      summary: Initialize user session
      description: Initialize user session with device and region information
      operationId: startHeaderInfo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartHeaderInfo'
      responses:
        '200':
          description: Session successfully initialized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartHeaderResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /nav/data:
    get:
      summary: Get navigation structure
      description: Retrieve hierarchical navigation structure
      operationId: getNavigationData
      parameters:
        - name: language
          in: query
          schema:
            type: string
          description: Preferred language for navigation labels
      responses:
        '200':
          description: Navigation structure retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NavigationData'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /apa/asset:
    get:
      summary: Get asset configuration
      description: Get device-specific asset configurations
      operationId: getAssetConfig
      parameters:
        - name: deviceType
          in: query
          required: true
          schema:
            type: string
          description: Type of device requesting asset configuration
        - name: assetId
          in: query
          required: true
          schema:
            type: string
          description: Unique identifier of the asset
      responses:
        '200':
          description: Asset configuration retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetConfig'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /apa/metadata:
    get:
      summary: Get metadata configuration
      description: Retrieve content metadata and parameters
      operationId: getMetadataConfig
      parameters:
        - name: contentType
          in: query
          required: true
          schema:
            type: string
          description: Type of content (movie, series, episode, etc.)
        - name: language
          in: query
          schema:
            type: string
          description: Preferred language for metadata
      responses:
        '200':
          description: Metadata configuration retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataConfig'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
